# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/blevesearch/bleve";
    fetch = {
      type = "git";
      url = "https://github.com/blevesearch/bleve";
      rev = "67c3a1fa5884bc2ba7d9f4d362e5d435594a5a0d";
      sha256 = "09siw74q5iwy551wwn0s8kl4mla1qkb9c6m2inqs8l93l14haqhr";
    };
  }
  {
    goPackagePath = "github.com/gorilla/mux";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/mux";
      rev = "15a353a636720571d19e37b34a14499c3afa9991";
      sha256 = "1wx55r2j07bbp3q9p18r39dvf56kwdjvns62jiv4ax2kwla4wpf5";
    };
  }
  {
    goPackagePath = "github.com/mailru/easyjson";
    fetch = {
      type = "git";
      url = "https://github.com/mailru/easyjson";
      rev = "6243d8e04c3f819e79757e8bc3faa15c3cb27003";
      sha256 = "160sj5pq4bv9jshniimkd5f9zcg6xrbgb027lhr9l895nsv4dlib";
    };
  }
  {
    goPackagePath = "github.com/olivere/elastic";
    fetch = {
      type = "git";
      url = "https://github.com/olivere/elastic";
      rev = "f82cf7c66881f3f18d0354a68086e9aa2f9a48d1";
      sha256 = "1b3wad1kmvz16c9abzlpb32cxc113489pn59f6wx96n0ycrl70s6";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "ffb6e22f01932bf7ac35e0bad9be11f01d1c8685";
      sha256 = "197j5vpv03131rflygl7ks9bqbsx0sydq4bykw2hq0p6kg3grqzz";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "4ea4861398d99a2d05be29675c5b74caf7bea95e";
      sha256 = "1v65v7xpr2iqksxs2wz5amd4cf39l4z4rgqw9zijsrg6x0kyvicm";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "b01c7a72566457eb1420261cdafef86638fc3861";
      sha256 = "0snjjwlzsiakzs43pr4gv5wih5xgh9s2kwaq7gq208330fvqnpfk";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "c95aed5357e77a4bf7d3955c46740000a17adee1";
      sha256 = "0b1vjnzd67sp9lggs0yn9qfgp6f5djqgx40lyncd7j720q04kk2h";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "aca44879d5644da7c5b8ec6a1115e9b6ea6c40d9";
      sha256 = "106vs2md02h16rwnk9mq2h4ix7iyv2n6bfm7v9zp0kknswlag1x0";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "e6919f6577db79269a6443b9dc46d18f2238fb5d";
      sha256 = "1p830sa7zqv4vzan3sn34qgfzc8466glv5ln2w6la96yw70wwky3";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
